### ISSUE TITLE
Pootle manage.py deprecated?

### ISSUE THREAD

**Issue by arturh85** [evernote/serge#104]
(Pootle 2.8.2 with Serge master from yesterday)

I am new to Serge and Pootle, trying to install both i came across the following in the pootle integration documentation (https://serge.io/docs/guides/pootle/):

>manage_py_path is the path to manage.py script that comes with Pootle and serves as a command-line API for the local Pootle instance;

It is mandatory but I cannot find this manage.py Utility in my Pootle Installation, the only thing I found was this code which claimed it is deprecated:

https://github.com/translate/pootle/blob/master/manage.py

>warnings.warn("Deprecated. Use 'pootle' command instead", DeprecationWarning)

Are there any alternatives to using an older version of pootle? I tried using this deprecated manage.py anyway but it complains about missing SECRET_KEY Setting so it does not read my ~/.pootle/pootle.conf

I'm using the following docker container: https://github.com/arturh85/docker-pootle-serge

**Comment by iafan** [comment]
If you have installed Pootle from sources, then it will have the `manage.py` command. If you have it installed using pip, then its setup creates a `pootle` symlink in your $PATH. So for `manage_py_path` in your Serge config, you can either write just `pootle` or a full path to this executable (which you can determine by running `which pootle`).

Having said that, I'd recommend looking at using Zing instead of Pootle: https://github.com/evernote/zing — this is our fork of Pootle that was adapted to be used specifically with Serge, and we can provide a better support for it.

We also did some experimentation with using Serge in a Docker, so you may want to have a look at https://github.com/evernote/serge-dockerfiles. We don't use this approach in production, though; we also have this PR https://github.com/evernote/serge/pull/76 that might be a better source of inspiration; still have to review and merge it, though.

**Comment by arturh85** [comment]
Looks great @ zing, will try that as the continuous aspect is most important to me.
Setting manage_py_path to absolute path of pootle binary works, thank you!
