### ISSUE TITLE
Incorporate some level of encryption for passwords in the configuration file

### ISSUE THREAD

**Issue by icnocop** [evernote/serge#114]
Passwords are in plain text in the configuration file or in one or more environment variables.

For example, the database password or the password for the version control server (VCS).

I'm thinking there should be a better way to encrypt passwords that may appear in the configuration file(s) or environment variables, or acquire them from an external source.

For example, on Windows, maybe the Credential Manager can be used.

Thank you.

**Comment by iafan** [comment]
That's what environment variables are for. :)

Create a separate environment file with your password assigned to an environment variable (see #113), set proper permissions on that file for extra security (so that only the user under which Serge is run can read it) and have that file outside of your normal version control. Then reference these environment variables in your Serge config.

The files with secrets, especially if you have several servers, are something that is usually controlled by a deployment toolchain. Googling by "deploying secrets" should give a bunch of articles for further reading.

**Comment by icnocop** [comment]
Ok, great!

Thank you for the detailed explanation. :)
