### ISSUE TITLE
Add documentation on setting up Serge+Pootle

### ISSUE THREAD

**Issue by prat0088** [evernote/serge#12]
I'm new to Pootle.  Everything I have read, and my short experience tells me, that I need a templates/blah.pot file for =pootle update_store= to correctly load my new translations.  I can't find any mention of that in Serge's documentation or source code.  How are you getting translations into serge?

My current directory is just 'serge_test_proj/jpn/blah.po' and that isn't getting picked up.  When I add a .pot file by hand, it does.

**Comment by iafan** [comment]
First of all, you don't need .pot files for that, Serge syncs .po files with Pootle.

Pootle expects a certain folder structure in order to work properly. Here's an example:

```
/pootle_root_po_dir
    /project1
        /de_DE
            /resources.json.po
        /ja_JP
            /resources.json.po
        /ru_RU
            /resources.json.po
        ...
    /project2
        /de_DE
            /resources.xml.po
        /ja_JP
            /resources.xml.po
        /ru_RU
            /resources.xml.po
        ...
   ...
```

and in your Pootle configuration file you need to set the path to `/pootle_root_po_dir`

In your Serge config for your "Project 1" you need to specify:

```nginx
ts_file_path                /pootle_root_po_dir/project1/%LOCALE%/%FILE%.po
```

so that Serge generates .po files the way Pootle expects them. On Pootle side, you need to go to your Admin panel => Projects and create a new project with id `project1` (this is how Pootle will know that it needs to look inside `/pootle_root_po_dir/project1` folder).

When this is configured, Serge will do the two-way sync with Pootle automatically using it's `sync_stores` and `update_stores` commands. All you need to do in your Serge config is to add the following section:

```nginx
sync
{
    ts
    {
        plugin                      pootle

        data
        {
            manage_py_path          /path/to/pootle/manage.py
            project_id              project1
        }
    }

    ...
}
```

**Comment by iafan** [comment]
I'll keep this open till I add the above mentioned short tutorial to Serge's `pootle` plugin documentation.

**Comment by julen** [comment]
@iafan out of curiosity: does the plugin take virtual environments into account? If one runs `manage.py` directly, the first Python interpreter found in `PATH` will be used, which won't match the intended interpreter if using virtual environments.

Also, if users installed Pootle via pip, they will have the `pootle` command available, which serves the same purpose as `manage.py` (note the latter will be buried somewhere under the Python installation subdirectories). So how does one specify to use the `pootle` command in that case? Does it happen automatically?

**Comment by iafan** [comment]
Good point, @julen!

1. If Pootle is installed from under virtualenv, you need to make sure that `manage.py` is being run in the context of this environment (one can create a wrapper shell script to select this environment and call the script itself).

2. If in your system there's a script called `pootle` instead of `manage.py`, then use it.

Basically, you need to tell Serge a path to some script that will consume `sync_stores` and `update_stores` commands and properly run them against the installed Pootle instance. Serge doesn't try to be overly smart about detecting system configuration.

**Comment by prat0088** [comment]
Thanks for the reply.  I think I got most of that on my own after some digging.  It turns out my problem was the language.  I was specifying "jpn" for Japanese in my .serge file.  Pootle was expecting the directory 'ja', not 'jpn' for the .po files.

**Comment by iafan** [comment]
Added relevant documentation: https://serge.io/docs/guides/pootle/
