### ISSUE TITLE
Qt Text Id based (ts files)

### ISSUE THREAD

**Issue by Amf1k** [evernote/serge#122]
Does the parser support Text ID Based Translations in .ts files (Qt5)?

**Comment by iafan** [comment]
I'm not familiar with Qt, but as far as I understand from https://doc.qt.io/qt-5/linguist-id-based-i18n.html, Text IDs is just a way to address strings in the code (by using their IDs, not the actual text. Regardless of the approach, the `lupdate` tool, which is a part of Qt, will extract strings into resource files (.ts), and the format of this file remains the same.

Serge has a parser for Qt .ts files: https://serge.io/docs/plugins/parser/parse_ts/

**Comment by Amf1k** [comment]
the question is, will the parser lose the id attribute of the message element?

**Comment by iafan** [comment]
No, the only thing it does is it replaces the contents of the `<translation>` tag and removes its `type` attribute ([see the code](https://github.com/evernote/serge/blob/master/lib/Serge/Engine/Plugin/parse_ts.pm#L163-L165)). Otherwise, the entire XML file structure should be preserved. Let me know if this is not the case, and I'll have a look.

**Comment by Amf1k** [comment]
Ok. i check it

**Comment by iafan** [comment]
I assume the parser plugin works as expected, so I'll close this issue. But feel free to re-open if you still have troubles using it.
