### ISSUE TITLE
Can someone create a sample config file that convert a resource file and generate PO?

### ISSUE THREAD

**Issue by whereisjim** [evernote/serge#31]
Hi,

Can someone please share a config file that just pick up a resource file from local and output a PO file?
Still somewhat confused all the fields in configuration reference file and looking for some small sample config file that will help me to get started.
TIA.

**Comment by iafan** [comment]
Please have a look at tests inside [<serge_root>/t/data/engine](https://github.com/evernote/serge/tree/master/t/data/engine) — there you will see sample localization projects per each parser, and also the ones that showcase the use of control plugins. The only difference from real-life projects is that these tests use in-memory SQLite database, while for production you need to specify a [path to your SQLite file](https://serge.io/docs/configuration-files/reference/#sel:I2NvZGVfMC9zcGFuLjk2NjgvQC0jY29kZV8wL3NwYW4uOTcyNS9AOjE) rather than `:memory:`

What resource files do you have, specifically?

**Comment by iafan** [comment]
I'm closing the issue now, but feel free to reopen or comment on it if you have further questions.
