### ISSUE TITLE
First config serge

### ISSUE THREAD

**Issue by greydjin** [evernote/serge#32]
Hello.
I do not understand the reasons for the error. Maybe it's easy and you can tell?
`root@Kholodkov-VM:/home/andre/serge/serge/t/data/engine# serge import Pootletest.serge

*** /home/andre/serge/serge/t/data/engine/Pootletest.serge ***

*** [raketa] Process git file project ***

Path to source resources: [/home/andre/translations/Pootletest/vcs/docs]
Path to localized resources: [/home/andre/translations/Pootletest/%NAME%.%EXT%]
Languages: [en,ru]
DB source: []
Preloading cache for job 'raketa' in namespace 'Pootletest'...
Can't call method "prepare" on an undefined value at /home/andre/serge/serge/bin/../lib/Serge/DB.pm line 286.`
My Pootletest.serge file http://pastebin.com/bbNmZAdw

**Comment by iafan** [comment]
You have an empty DB source:

```
DB source: []
```

This could be either because you have it empty in your config file initially (see [db_source](https://serge.io/docs/configuration-files/reference/#sel:I2NvZGVfMC9zcGFuLjk1NTMvQC0jY29kZV8wL3NwYW4uMTAyMjUvQDox) config parameter), or you have an environment variable there that evaluates to an empty value.

I think Serge needs to bail out with a meaningful error message in this case earlier. I'll look into adding this kind of check to the job validator.

**Comment by iafan** [comment]
I pushed a few commits, including https://github.com/evernote/serge/commit/fbf9ba1fa3a9a2ba946472f3d4cd3bd250125b00, that should now provide descriptive error message when `db_source` is empty. I'm closing the issue as I believe it is answered, but feel free to follow up here or on IRC if you still have issues setting things up.
