### ISSUE TITLE
Good ways to handle DB strings?

### ISSUE THREAD

**Issue by zdlgrj** [evernote/serge#47]
Hi,

We are looking into potentially using serge as part of our continuous localization platform, and we are utilizing the basic SOA architecture with strings stored in DB(Mongo) that needs to be localized. Wonder is there a good way to handle that using serge?

What we have been planning is:

1. When service A persist strings in the DB that needs to be translated, embrace it with certain marker.

2. Having a cron job running in the backend constantly pulling the strings that needs to be translated from DB to localization resource file that will be feed into the translation workflow. 

3. When service B calls GET request to service B for retrieving certain content with strings need to be localized, service B need to pass the locale info as part of the request. In the business logic of Service A, it queries the DB first, and for the fields that have the localized mark, ask the translated resource file to get the translated string based on local.

Wonder how do you achieve similar localization workflow in Evernote within Service-Oriented architecture? Is anything serger can help to make it easier?

Thanks!

**Comment by prat0088** [comment]
I'm not with Evernote, but we have plans to roll out Serge to many databases.

My situation is a bit different because we're using SQL and our biggest challenge is scaling this across different teams with different database schemas.  We have services for querying, but not for writing, so we made our interface a directory of .csv files that Serge monitors.  We leave it to the engineer to dump and load the appropriate columns for translation. 

If I only had to do this for one database I would consider writing a VSC plugin that interfaced directly with the database and query to a .po/.csv file that gets parsed by a regular Serge parser plugin.  It might break some of your nice service boundaries but I personally prefer this method because it is simple and direct.

Having said that, I think your plan seems reasonable.

**Comment by iafan** [comment]
@zdlgrj the approach largely depends on the nature of the strings to translate. Does service A populate the DB from some external (users') data? Or are these simply application resources?

For app resources, it should be easier to have resource files committed to version control system, from which Serge would pick them up. This would allow to skip the DB altogether and simplify the whole setup.

If strings come from users and absolutely have to be stored in the DB, then you will need to implement some additional mechanism (either a specific VCS plugin, or a standalone script) that would pull changes from your DB into a local file system and then push changes from local files back to the DB. We at Evernote use the standalone sync script approach as it is easier to implement and maintain and is less coupled with Serge. We have sync scripts for Zendesk and Google Docs, and this is how they work in general (let's take Zendesk sync script as an example):

When Zendesk sync script is executed, it downloads all the updated Knowledge Base articles and saves them as individual files. Then we push changes to Git (working through Git also allows to effectively backup all the content we generate and keep the entire history of changes in case we need to roll back something). Once files are in Git, they can be picked up by Serge. Serge generates localized versions of these files. The same Zendesk script, when run next time, detects all the modified files and pushes them back to Zendesk as localized copies of Knowledge Base articles.

---

The item 3 on your list seems a bit complicated to me (e.g. querying the DB first and then doing a fallback to read from files?). If you implement the sync script similar to the one I described above, you should be able to just query the DB to get all the localized resources (and fall back to English resources otherwise). Or, if you can export localizations to resources files, work completely off resource files without querying the DB at all — this should be much faster. Note that when Serge generates localized resources, it leaves strings in English if they don't have translations yet. So localized files, even if partially translated, always have all the strings, so that you don't have to implement a dynamic fallback mechanism. Of course, one can change this behavior if needed. 

So it would be great to get some more background information on the kind of strings to be translated. Then we can refine the approach.

P.S.: I'm on a vacation for another week, so expect some delay with the answers.

**Comment by zdlgrj** [comment]
@iafan Thanks for your information.

As you said, for application resource, yes, it should be much easier to integrate with the localization workflow by skipping the DB part. We do have some use cases which we can just utilize the application resources.

But on the other hand, we also have some services that need to take strings from users, and stored in the DB, and the content needs to be queried through the service. As we summarized, there could be multiple options for those strings to be localized as below:

**1)** Use DB Strings as the source of the truth, write some standalone script or plugin to pull the changes from DB, and then push the changes to Git to trigger the localization workflow.  When do a GET for the service, it queries DB directly for localized content.

Concerns: I have mixed feeling about this approach as we have to store the different translated content in the DB for the sample copy of model. Even though the model could be normalized to some extent, but might need some level refactor of the existing model.

**2)** Externalize all localizable strings from DB to resource files, and work only with resource files for localized strings.

Concerns/Thoughts: For the most of time, we only want to localize certain fields within some existing DB models. We probably still need to query DB for most of the non-localized fields with existing relation. That is actually what I originally propose by "querying the DB first" and "for the fields with localized mark, check resource file".

For example, let s say we have a model similar to below:

```
Plan
--------
planId:xxxxx -> PK
displayName: "Test Plan" -> Field that needs to be localized
productID:xxx -> FK to product
price:xxx
createdOn:xxx
```

Given said for option 2), I am thinking if it s better to just change the logic on persistent layer that we query the plan first, and detect the displayName is "localizable", then we go to resource files to find the translated content with given locale(if not, fallback to English). Basically it is constructing the `Plan` object from both DB and resource files in this way. I feel this could be a good option but I am not crazy about this approach either as it complicates the logic of repository layer.

We are still in the experiment phase, trying to weigh between different approaches. Any ideas or suggestion would be appreciated!

**Comment by zdlgrj** [comment]
@prat0088  thanks for your reply.

For the approach you mentioned above for using a script/plugin pulling the content from database to   resource files, when you do querying, do you directly read everything from database or resource files? or mixed query for DB and resource file? (Please see the `Plan` example I posted above).

**Comment by iafan** [comment]
>  store the different translated content in the DB for the sample copy of model

Not sure if I got this right, but does this mean you want to have e.g. different translations for the same source string for different users?

---

First of all, I generally prefer going with some more or less static approach to localization (e.g. resource files), because it is usually faster. But _only if_ it doesn't complicate the business logic of the app. So if your localizable content has a dynamic nature and if you can store it in the database efficiently (so that rendering the localized UI doesn't affect the performance much), then it's better to keep the strings in the DB. But even if you store your source strings and final translations in the database, it might make sense to export them into intermediate files for translation instead of altering the DB directly.

So these are the things to think about:

1. What is the ideal way to store translations in the database so that you could query them effectively (ideally, get your model data + localizations in one step by simply joining some extra table by the primary key).
2. What is the ideal way to map the source strings and translations as files.

To implement an effective DB <=> resource file synchronization mechanism, your models should better have some unique sequence number (USN) to be able to effectively select everything that was modified past a certain point. Last update timestamp might be used as a surrogate USN, though using dates can be tricky, and it's better to have real USNs in place. Also, to avoid generating huge resource files for each small change, I'd recommend thinking about some logical separation that would help not only implement an efficient sync mechanism, but also provide some context for translators.

For example—and I'm totally making this up—you have customers, each having their products and product features/properties (like parts of the UI, or a list of paid plans). A model knows which fields are translatable, and instead of storing the value in the model, stores a `string_id` (PK) that references a row in a `strings` table. Now, you have a `translations` table that in turn has the same `string_id` reference, `user_id` reference, reference to the locale and the actual translation. With this, when selecting data for your model, you can get both related source strings and translations for the given user and language easily, and when rendering the data for the user, display a translation or fall back to source string if translations are missing.

Based on the contents in `strings` table (and again, rows there need to have USNs which would increment on any string addition or change), one should be able to easily update the resource files that could have paths like `/en/<user_name>/<product_name>.json` or  `/en/<user_id>/<product_name>/<feature_name>.json` (provided you are using JSON as a file format to store translations, but you can have literally anything that is easy to deal with from your sync script code). The smaller the files and the more understandable  the scope is, the better. With that in place, Serge can work with these json files and generate localized files named e.g. `/<language>/<user_id>/<product_name>/<feature_name>.json`. Your sync script can then detect the changes done to certain files (by comparing file modification time between runs) and update translations in your database.

**Comment by prat0088** [comment]
@zdlgrj Sorry for the late reply.

In my case, the process that exports translations from the DB to resource files runs whenever the database is updated.  In our case it's easy because the databases usually update on a fixed schedule several times per day.  That job also re-imports data from the localized resource files.

In my configuration, Serge will interact exclusively with the resource files.  It knows nothing about the source DB.  This is a feature for us since we have to support multiple databases using different technology and having different-but-related schemas.

See also @iafan 's great reply.

**Comment by iafan** [comment]
Closing a stalled issue that has been answered.
