### ISSUE TITLE
How to keep the order of the 'key' when using 'parse_json_keyvalue'?

### ISSUE THREAD

**Issue by whereisjim** [evernote/serge#61]
Using 'parse_json_keyvalue' parser, the output file comes out as with 'key' value alphabetically sorted.
Is there a way to keep the original English order as is?

I don't think it will break the function, but for troubleshooting, visual diff, debugging and etc with English source file, it would be great if we can keep the original English order as is.

**Comment by iafan** [comment]
This is the way this specific parser works (because internally it uses the standard JSON Perl library): it is a fully validating parser, and it creates an in-memory tree representation of the JSON document. The ordering of keys in memory and in the output is not guaranteed, so to make sure Serge provides stable JSON output and to avoid random commits to version control, we have to sort keys.

In order to maintain the order of the keys, we'd need to create a custom JSON parser, which, I believe, is not worth the effort, especially, as you already pointed out, the ordering of the keys should not have any effect on the functionality and is not guaranteed according to JSON spec.

However, there might be a simple solution to your problem: if your JSON file represents a flat object with keys and values, you can use the [parse_js](https://serge.io/docs/plugins/parser/parse_js/) parser instead. This parser user regular expressions and retains the original structure of the document (which means the order of the keys will also be preserved).

Another way to preserve the order is to [redefine your JSON data structure](http://stackoverflow.com/a/4515863) (use an array of objects, not one object), but this might require changes in runtime code, and is probably not worth the effort either.

**Comment by whereisjim** [comment]
Switching to 'parse_js' did the trick.

Thank you.
