### ISSUE TITLE
Reuse translations only for strings from the same file path and context and namespace

### ISSUE THREAD

**Issue by prat0088** [evernote/serge#64]
The current reuse_translations code is pretty loose.  It will re-use translations even if it finds one string from a file of a different name in a different namespace with the same context.

What I would like is a way to limit reuse only to the same file in a namespace.  Essentially, only reuse if all of the following are true:

- Namespaces match
- File paths match
- Contexts match
- Source strings match

I would need to modify find_best_translation() and add a new option to the job configurations: reuse_fairly_certain , or maybe make each matching criteria an option:

- reuse_requires_matching_namespaces
- reuse_requires_matching_filepaths
- ...

Would you accept a pull request for this?

**Comment by iafan** [comment]
As I can understand from your explanation, you would prefer not to do any reuse between files. I also remember that your translation files are exported from the DB, so I assume that each file encapsulates the entirety of strings in some project, and so essentially you'd prefer to isolate those projects. Am I correct?

Now how this string reuse was originally laid out:
1. Serge reuses whatever translations you have in its TM database, but takes namespaces/files/contexts into consideration to find the best match in case there are multiple candidates.
2. It is expected that if one wants to prevent translation reuse across projects, they can just use different databases. Having multiple databases is cheap (especially if you use SQLite databases, which are created on the fly), and you have an ability to set databases on a per-job level. If you set up your jobs so that each one processes just a single file, you will get that per-file TM reuse granularity.

The approach with multiple translation databases is very flexible:
1. You have full control which jobs write to which database, so you can group jobs A and B into one database (and thus allow sharing translations between them), and then give job C its own database which won't be reused with any other job.
2. Splitting Serge jobs into multiple databases allows you to scale your localization infrastructure: You can run multiple `serge sync` cycles for each database in parallel, and reduce each sync cycle.

So I believe Serge already addresses your use case, but let me know if you feel that your approach adds some extra benefits.

**Comment by iafan** [comment]
Closing a stalled issue that has been answered.
