### ISSUE TITLE
JSON (key-value) files are outputted with BOM, making them invalid JSON

### ISSUE THREAD

**Issue by bearfriend** [evernote/serge#82]
JSON key-value files are outputted with BOM, making them invalid JSON. Can this be turned off? Is there a reason for this?

https://github.com/evernote/serge/blob/master/t/data/engine/parse_json_keyvalue/00/translate.serge#L15

**Comment by iafan** [comment]
It looks like you've figured it out, but the `output_bom` parameter is something provided by the Serge core, and it can be turned on or off independently of the parser. For some output formats the BOM might not be needed, doesn't make sense or is illegal (as in JSON). In the test above it doesn't really matter (and this was likely a copy-paste from some other test), but I agree that this might be confusing. I'll reopen the ticket and have this setting remove from JSON tests so that they more closely resemble real-life use of such parser.

**Comment by iafan** [comment]
I cleaned up the test to get rid of `output_bom YES` parameter.
